/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb780",
        "on-secondary-fixed-variant": "#6f3800",
        "surface-container-low": "#2a1612",
        "on-tertiary-fixed": "#211b05",
        "secondary-fixed": "#ffdcc4",
        "tertiary-fixed": "#efe2be",
        "secondary-container": "#7c4001",
        "on-background": "#ffdad2",
        "tertiary-fixed-dim": "#d2c6a3",
        "on-secondary": "#4e2600",
        "on-surface": "#ffdad2",
        tertiary: "#daceab",
        "inverse-primary": "#735c00",
        "on-primary": "#3c2f00",
        surface: "#210e0a",
        "on-tertiary-container": "#4c452a",
        "tertiary-container": "#beb291",
        "primary-fixed-dim": "#e9c349",
        "inverse-on-surface": "#412b25",
        "outline-variant": "#4d4635",
        "surface-container": "#2f1a15",
        "on-tertiary-fixed-variant": "#4e462c",
        "error-container": "#93000a",
        "surface-tint": "#e9c349",
        secondary: "#ffb780",
        "surface-variant": "#462f29",
        "primary-container": "#d4af37",
        "on-primary-fixed": "#241a00",
        "on-secondary-fixed": "#2f1400",
        primary: "#f2ca50",
        "surface-bright": "#4b332e",
        "on-secondary-container": "#ffb275",
        outline: "#99907c",
        "on-primary-container": "#554300",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#574500",
        "surface-container-highest": "#462f29",
        "inverse-surface": "#ffdad2",
        "on-surface-variant": "#d0c5af",
        "primary-fixed": "#ffe088",
        "on-tertiary": "#373018",
        "surface-container-lowest": "#1b0906",
        error: "#ffb4ab",
        "surface-container-high": "#3a251f",
        "on-error": "#690005",
        "surface-dim": "#210e0a",
        background: "#210e0a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Newsreader", "serif"],
        label: ["Work Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
