services:
  # 1. Veritabanı Servisi
  postgres:
    image: postgres:16-alpine
    container_name: hogsmade-db
    environment:
      POSTGRES_DB: hogsmade_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d hogsmade_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - hogsmade-net

  # 2. Backend Servisi (Spring Boot)
  backend:
    build:
      context: ./hogsmadecafe
      dockerfile: Dockerfile
    container_name: hogsmade-api
    # Veritabanı tamamen hazır olmadan Spring Boot'u başlatmaz
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # ÖNEMLİ: jdbc:postgresql:// servis_adi : port / db_adi
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hogsmade_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "8081:8080" # Jenkins 8080'de olduğu için dışarıyı 8081 yaptık
    networks:
      - hogsmade-net

  # 3. Frontend Servisi (React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hogsmade-ui
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - hogsmade-net

networks:
  hogsmade-net:
    driver: bridge

volumes:
  postgres_data: